<?php 
   // Categorias
   $categorias = [
     'Estética' => [
    ['name' => 'Leave-in Restaurador', 'price' => '49.90', 'image' => '../imagens/produtos/leaveinRestaurador.webp'],
    ['name' => 'Kit de Shampoo', 'price' => '79.90', 'image' => '../imagens/produtos/kitShampoo.webp'],
    ['name' => 'Lip Tint', 'price' => '39.90', 'image' => '../imagens/produtos/lipTint.webp'],
    ['name' => 'Máscara Capilar', 'price' => '59.90', 'image' => '../imagens/produtos/mascaraCapilar.webp'],
    ['name' => 'Protetor Solar', 'price' => '59.90', 'image' => '../imagens/produtos/protetorSolar.webp'],
    ['name' => 'Esmalte', 'price' => '4.90', 'image' => '../imagens/produtos/esmalte.webp'],
    ['name' => 'Kit Anti-Frizz', 'price' => '89.90', 'image' => '../imagens/produtos/kitAntiFrizz.webp'],
    ['name' => 'Óleo Capilar', 'price' => '49.90', 'image' => '../imagens/produtos/oleoCapilar.webp'],
    ['name' => 'Creme de Cabelo', 'price' => '29.90', 'image' => '../imagens/produtos/cremedecabelo.webp'],
    ['name' => 'Shampoo e Condicionador 50ml', 'price' => '29.90', 'image' => '../imagens/produtos/shampooEcondicionador.webp'],
    ['name' => 'Enxaguante Bucal', 'price' => '14.90', 'image' => '../imagens/produtos/enxaguanteBucal.webp'],
    ['name' => 'Fio Dental', 'price' => '9.90', 'image' => '../imagens/produtos/fioDental.webp'],
    ['name' => 'Protetor Solar Facial Creme', 'price' => '79.90', 'image' => '../imagens/produtos/protetorSolarFacial.webp'],
    ['name' => 'Condicionador Eudora', 'price' => '44.90', 'image' => '../imagens/produtos/condicionadorEudora.webp'],
    ['name' => 'Creme Para Pentear', 'price' => '34.90', 'image' => '../imagens/produtos/cremeParaPentear.webp'],
    ['name' => 'Ampola Capilar Pantene', 'price' => '19.90', 'image' => '../imagens/produtos/ampolaCapilar.webp'],
    ['name' => 'Shampoo Matizador', 'price' => '54.90', 'image' => '../imagens/produtos/shampooMatizador.webp'],
    ['name' => 'Gelatina Capilar', 'price' => '39.90', 'image' => '../imagens/produtos/gelatinaCapilar.webp'],
    ['name' => 'Tônico Capilar', 'price' => '69.90', 'image' => '../imagens/produtos/tonicoCapilar.webp'],
    ['name' => 'Shampoo Antiqueda', 'price' => '59.90', 'image' => '../imagens/produtos/shampooAntiqueda.webp'],
    ['name' => 'Óleo Finalizador', 'price' => '49.90', 'image' => '../imagens/produtos/oleoFinalizador.webp'],
    ['name' => 'Creme Clareador', 'price' => '39.90', 'image' => '../imagens/produtos/cremeClareador.webp'],
    ['name' => 'Creme Multirreparador', 'price' => '49.90', 'image' => '../imagens/produtos/cremeMultirreparador.webp'],
    ['name' => 'Pó Compacto', 'price' => '34.90', 'image' => '../imagens/produtos/poCompacto.webp'],
    ['name' => 'Base Líquida Dailus', 'price' => '39.90', 'image' => '../imagens/produtos/baseLiquidaDailus.webp'],
    ['name' => 'Tinta de Cabelo', 'price' => '19.90', 'image' => '../imagens/produtos/tintaDeCabelo.webp'],
    ['name' => 'Sérum Facial', 'price' => '79.90', 'image' => '../imagens/produtos/serumFacial.webp'],
    ['name' => 'Condicionador Pantene', 'price' => '39.90', 'image' => '../imagens/produtos/condicionadorPantene.webp'],
    ['name' => 'Kit Principia Anti-Acne', 'price' => '89.90', 'image' => '../imagens/produtos/kitAntiAcne.webp'],
    ['name' => 'Paleta Multifuncional', 'price' => '89.90', 'image' => '../imagens/produtos/paletaMultifuncional.webp'],
    ['name' => 'Sérum Reparador Capilar', 'price' => '69.90', 'image' => '../imagens/produtos/serumReparador.webp'],
    ['name' => 'Corretivo Líquido Ruby Rose', 'price' => '24.90', 'image' => '../imagens/produtos/corretivoLiquido.webp'],
    ['name' => 'Máscara de Cílios Melu', 'price' => '34.90', 'image' => '../imagens/produtos/mascaraDeCilios.webp'],
    ['name' => 'Paleta de Sombras', 'price' => '79.90', 'image' => '../imagens/produtos/paletaDeSombras.webp'],
    ['name' => 'Máscara Esfoliante Para Pés', 'price' => '29.90', 'image' => '../imagens/produtos/mascaraEsfoliante.webp'],
],

       
     'Medicinal' => [
    ['name' => 'Rinosoro', 'price' => '19.90', 'image' => '../imagens/produtos/rinosoro.webp'],
    ['name' => 'Anador', 'price' => '14.90', 'image' => '../imagens/produtos/anador.webp'],
    ['name' => 'Apracur Duo', 'price' => '24.90', 'image' => '../imagens/produtos/ApracurDuo.webp'],
    ['name' => 'Soro Fisiológico', 'price' => '9.90', 'image' => '../imagens/produtos/soroFisiologico.webp'],
    ['name' => 'Autoteste Covid', 'price' => '30.90', 'image' => '../imagens/produtos/autotesteCovid.webp'],
    ['name' => 'Oxímetro', 'price' => '59.90', 'image' => '../imagens/produtos/oximetro.webp'],
    ['name' => 'Bromazepam', 'price' => '29.90', 'image' => '../imagens/produtos/bromazepam.webp'],
    ['name' => 'Buscofem', 'price' => '15.90', 'image' => '../imagens/produtos/buscofem.webp'],
    ['name' => 'Buscopan', 'price' => '19.90', 'image' => '../imagens/produtos/buscopan.webp'],
    ['name' => 'Cefadrin', 'price' => '49.90', 'image' => '../imagens/produtos/cefadrin.webp'],
    ['name' => 'Cimegripe', 'price' => '29.90', 'image' => '../imagens/produtos/cimegripe.webp'],
    ['name' => 'Neosaldina', 'price' => '21.90', 'image' => '../imagens/produtos/neosaldina.webp'],
    ['name' => 'Compressa de Gaze', 'price' => '5.90', 'image' => '../imagens/produtos/compressaDeGaze.webp'],
    ['name' => 'Curativo Hidrocoloide', 'price' => '29.90', 'image' => '../imagens/produtos/curativoHidrocoloide.webp'],
    ['name' => 'Deciprax Oxalato', 'price' => '39.90', 'image' => '../imagens/produtos/decipraxOxalato.webp'],
    ['name' => 'Naldecon Multi', 'price' => '19.90', 'image' => '../imagens/produtos/naldeconMulti.webp'],
    ['name' => 'Desloratadina', 'price' => '22.90', 'image' => '../imagens/produtos/desloratadina.webp'],
    ['name' => 'Multigrip', 'price' => '29.90', 'image' => '../imagens/produtos/multigrip.webp'],
    ['name' => 'Monitor de Pressão', 'price' => '79.90', 'image' => '../imagens/produtos/monitordepressão.webp'],
    ['name' => 'Dipirona', 'price' => '7.90', 'image' => '../imagens/produtos/dipirona.webp'],
    ['name' => 'Dorflex', 'price' => '19.90', 'image' => '../imagens/produtos/dorflex.webp'],
    ['name' => 'Doril', 'price' => '15.90', 'image' => '../imagens/produtos/doril.webp'],
    ['name' => 'Esalerg', 'price' => '24.90', 'image' => '../imagens/produtos/Esalerg.webp'],
    ['name' => 'Tylenol', 'price' => '19.90', 'image' => '../imagens/produtos/tylenol.webp'],
    ['name' => 'Esparadrapo', 'price' => '4.90', 'image' => '../imagens/produtos/esparadrapo.webp'],
    ['name' => 'Extrato de Própolis', 'price' => '29.90', 'image' => '../imagens/produtos/extratodepropolis.webp'],
    ['name' => 'Fendizoato de Cloperastina', 'price' => '19.90', 'image' => '../imagens/produtos/fendizoatoDeCloperastina.webp'],
    ['name' => 'Fita Microporosa', 'price' => '6.90', 'image' => '../imagens/produtos/fitaMicroporosa.webp'],
    ['name' => 'Floral de Bach', 'price' => '29.90', 'image' => '../imagens/produtos/floralDeBach.webp'],
    ['name' => 'Grip7', 'price' => '19.90', 'image' => '../imagens/produtos/grip7.webp'],
    ['name' => 'Luftal Gel', 'price' => '29.90', 'image' => '../imagens/produtos/luftalGel.webp'],
    ['name' => 'Spray para Garganta', 'price' => '39.90', 'image' => '../imagens/produtos/sprayparagarganta.webp'],
    ['name' => 'Maxalgina (Dipirona)', 'price' => '16.90', 'image' => '../imagens/produtos/maxalginaDipirona.webp'],
    ['name' => 'Trauma C Aerossol', 'price' => '24.90', 'image' => '../imagens/produtos/traumacAerossol.webp'],
    ['name' => 'Permetrina', 'price' => '49.90', 'image' => '../imagens/produtos/permetrina.webp'],
],

   
     'Nutrição' => [
    ['name' => 'Condres Colágeno', 'price' => '79.90', 'image' => '../imagens/produtos/condresColageno.webp'],
    ['name' => 'Suplemento Alimentar', 'price' => '49.90', 'image' => '../imagens/produtos/suplementoAlimentar.webp'],
    ['name' => 'Cálcio', 'price' => '29.90', 'image' => '../imagens/produtos/calcio.webp'],
    ['name' => 'Complemento Alimentar', 'price' => '39.90', 'image' => '../imagens/produtos/complementoAlimentar.webp'],
    ['name' => 'Multivitaminico Infantil', 'price' => '59.90', 'image' => '../imagens/produtos/multivitaminicoInfantil.webp'],
    ['name' => 'Suplemento Vitaminico', 'price' => '49.90', 'image' => '../imagens/produtos/suplementoVitaminico.webp'],
    ['name' => 'Creatina', 'price' => '89.90', 'image' => '../imagens/produtos/creatina.webp'],
    ['name' => 'Whey Protein (morango)', 'price' => '149.90', 'image' => '../imagens/produtos/wheyProtein.webp'],
    ['name' => 'Proteina em pó', 'price' => '129.90', 'image' => '../imagens/produtos/proteinaEmPo.webp'],
    ['name' => 'Vitamina D', 'price' => '29.90', 'image' => '../imagens/produtos/vitaminaD.webp'],
    ['name' => 'Vitamina B12', 'price' => '29.90', 'image' => '../imagens/produtos/vitaminaB12.webp'],
    ['name' => 'Colágeno Tipo 2', 'price' => '89.90', 'image' => '../imagens/produtos/colagenoTipo2.webp'],
    ['name' => 'Ômega 3 VITAFOR', 'price' => '69.90', 'image' => '../imagens/produtos/omega3.webp'],
    ['name' => 'Coenzima Q10 Vitamina E', 'price' => '69.90', 'image' => '../imagens/produtos/coenzima.webp'],
    ['name' => 'Magnésio TREONATO', 'price' => '89.90', 'image' => '../imagens/produtos/magnesio.webp'],
    ['name' => 'Kit Vitamina D', 'price' => '79.90', 'image' => '../imagens/produtos/kitVitaminaD.webp'],
    ['name' => 'Restaure 15ml- Vitamina A, D3, E e K2', 'price' => '49.90', 'image' => '../imagens/produtos/restaure.webp'],
    ['name' => 'Vitamina C + Óleo de coco', 'price' => '59.90', 'image' => '../imagens/produtos/vitaminaC.webp'],
    ['name' => 'Vitamina K2', 'price' => '49.90', 'image' => '../imagens/produtos/vitaminaK2.webp'],
    ['name' => 'Body Protein', 'price' => '79.90', 'image' => '../imagens/produtos/bodyProtein.webp'],
    ['name' => 'Colágeno Semblé', 'price' => '79.90', 'image' => '../imagens/produtos/colageno.webp'],
    ['name' => 'Barra de Proteína Fit Brownie', 'price' => '29.90', 'image' => '../imagens/produtos/barradeproteina.webp'],
    ['name' => 'Polivitamínico Centrum', 'price' => '79.90', 'image' => '../imagens/produtos/polivitaminicoCentrum.webp'],
    ['name' => 'Zerolac', 'price' => '49.90', 'image' => '../imagens/produtos/zerolac.webp'],
    ['name' => 'Suplemento Alimentar Nestlé Baunilha', 'price' => '69.90', 'image' => '../imagens/produtos/suplementoAlimentarNestle.webp'],
    ['name' => 'Polivitamínico Gerovital', 'price' => '59.90', 'image' => '../imagens/produtos/polivitaminicoGerovital.webp'],
    ['name' => 'Vitamina C Efervescente', 'price' => '29.90', 'image' => '../imagens/produtos/vitaminaCefervescente.webp'],
    ['name' => 'Lactosil', 'price' => '29.90', 'image' => '../imagens/produtos/lactosil.webp'],
    ['name' => 'Sorox Frutas Vermelhas', 'price' => '29.90', 'image' => '../imagens/produtos/sorox.webp'],
    ['name' => 'Suplemento Alimentar Melatonina', 'price' => '39.90', 'image' => '../imagens/produtos/melatonina.webp'],
    ['name' => 'Bebida Engov Tangerina', 'price' => '19.90', 'image' => '../imagens/produtos/engov.webp'],
    ['name' => 'Fibra Alimentar Nestlé Sem Sabor', 'price' => '29.90', 'image' => '../imagens/produtos/fibraAlimentar.webp'],
    ['name' => 'Vitamina E', 'price' => '39.90', 'image' => '../imagens/produtos/vitaminaE.webp'],
    ['name' => 'Polivitamínico Luvis', 'price' => '39.90', 'image' => '../imagens/produtos/polivitaminicoLuvis.webp'],
    ['name' => 'Cálcio Prosso Tabletes', 'price' => '39.90', 'image' => '../imagens/produtos/calcioTabletes.webp'],
],

];

   