<?php 
   // Categorias
   $categorias = [
       'Estética' => [
           ['name' => 'Bolsa de Água Quente', 'price' => '39.90', 'image' => '../imagens/produtos/BolsaDeAguaquente.webp'],
           ['name' => 'Desodorante Vichy', 'price' => '39.90', 'image' => '../imagens/produtos/desodorantevichy.webp'],
           ['name' => 'Inalador', 'price' => '39.90', 'image' => '../imagens/produtos/inalador.webp'],
           ['name' => 'Termômetro Digital', 'price' => '39.90', 'image' => '../imagens/produtos/TermometroDigital.webp'],
           ['name' => 'Tornozeleira', 'price' => '39.90', 'image' => '../imagens/produtos/tornozeleira.webp'],
       ],
       
       'Medicinal' => [
           ['name' => 'Amoxicilina', 'price' => '39.90', 'image' => '../imagens/produtos/amoxicilina.webp'],
           ['name' => 'Anador', 'price' => '29.90', 'image' => '../imagens/produtos/anador.webp'],
           ['name' => 'Apracur Duo', 'price' => '29.90', 'image' => '../imagens/produtos/ApracurDuo.webp'],
           ['name' => 'Hidralazina (Apresolina)', 'price' => '19.90', 'image' => '../imagens/produtos/apresolinaHidralazina.webp'],
           ['name' => 'Autoteste Covid', 'price' => '39.90', 'image' => '../imagens/produtos/autotesteCovid.webp'],
           ['name' => 'Bezafibrato', 'price' => '39.90', 'image' => '../imagens/produtos/bezafibrato.webp'],
           ['name' => 'Bromazepam', 'price' => '39.90', 'image' => '../imagens/produtos/bromazepam.webp'],
           ['name' => 'Buscofem', 'price' => '39.90', 'image' => '../imagens/produtos/buscofem.webp'],
           ['name' => 'Buscopan', 'price' => '39.90', 'image' => '../imagens/produtos/buscopan.webp'],
           ['name' => 'Cefadrin', 'price' => '39.90', 'image' => '../imagens/produtos/cefadrin.webp'],
           ['name' => 'Cimegripe', 'price' => '39.90', 'image' => '../imagens/produtos/cimegripe.webp'],
           ['name' => 'Ciprofibrato', 'price' => '39.90', 'image' => '../imagens/produtos/ciprofibrato.webp'],
           ['name' => 'Compressa de Gaze', 'price' => '39.90', 'image' => '../imagens/produtos/compressaDeGaze.webp'],
           ['name' => 'Curativo Hidrocoloide', 'price' => '39.90', 'image' => '../imagens/produtos/curativoHidrocoloide.webp'],
           ['name' => 'Deciprax Oxalato', 'price' => '39.90', 'image' => '../imagens/produtos/decipraxOxalato.webp'],
           ['name' => 'Deprasil', 'price' => '39.90', 'image' => '../imagens/produtos/deprasil.webp'],
           ['name' => 'Desloratadina', 'price' => '39.90', 'image' => '../imagens/produtos/desloratadina.webp'],
           ['name' => 'Dexalgen', 'price' => '39.90', 'image' => '../imagens/produtos/dexalgen.webp'],
           ['name' => 'Diazepam', 'price' => '39.90', 'image' => '../imagens/produtos/diazepam.webp'],
           ['name' => 'Dipirona', 'price' => '39.90', 'image' => '../imagens/produtos/dipirona.webp'],
           ['name' => 'Dorflex', 'price' => '39.90', 'image' => '../imagens/produtos/dorflex.webp'],
           ['name' => 'Doril', 'price' => '39.90', 'image' => '../imagens/produtos/doril.webp'],
           ['name' => 'Esalerg', 'price' => '39.90', 'image' => '../imagens/produtos/Esalerg.webp'],
           ['name' => 'Esomeprazol', 'price' => '39.90', 'image' => '../imagens/produtos/esomeprazol.webp'],
           ['name' => 'Esparadrapo', 'price' => '39.90', 'image' => '../imagens/produtos/esparadrapo.webp'],
           ['name' => 'Extrato de Própolis', 'price' => '39.90', 'image' => '../imagens/produtos/extratodepropolis.webp'],
           ['name' => 'Fendizoato de Cloperastina', 'price' => '39.90', 'image' => '../imagens/produtos/fendizoatoDeCloperastina.webp'],
           ['name' => 'Fita Microporosa', 'price' => '39.90', 'image' => '../imagens/produtos/fitaMicroporosa.webp'],
           ['name' => 'Floral de Bach', 'price' => '39.90', 'image' => '../imagens/produtos/floralDeBach.webp'],
           ['name' => 'Grip7', 'price' => '39.90', 'image' => '../imagens/produtos/grip7.webp'],
           ['name' => 'Insulina', 'price' => '39.90', 'image' => '../imagens/produtos/insulina.webp'],
           ['name' => 'Losartana e Hidroclorotiazida', 'price' => '39.90', 'image' => '../imagens/produtos/losartanaeHidroclorotiazida.webp'],
           ['name' => 'Luftal Gel', 'price' => '39.90', 'image' => '../imagens/produtos/luftalGel.webp'],
           ['name' => 'Maxalgina (Dipirona)', 'price' => '39.90', 'image' => '../imagens/produtos/maxalginaDipirona.webp'],
           ['name' => 'Monitor de Pressão', 'price' => '39.90', 'image' => '../imagens/produtos/monitordepressão.webp'],
           ['name' => 'Multigrip', 'price' => '39.90', 'image' => '../imagens/produtos/multigrip.webp'],
           ['name' => 'Naire Bilastina', 'price' => '39.90', 'image' => '../imagens/produtos/naireBilastina.webp'],
           ['name' => 'Naldecon Multi', 'price' => '39.90', 'image' => '../imagens/produtos/naldeconMulti.webp'],
           ['name' => 'Neosaldina', 'price' => '39.90', 'image' => '../imagens/produtos/neosaldina.webp'],
           ['name' => 'Omeprazol', 'price' => '39.90', 'image' => '../imagens/produtos/omeprasol.webp'],
           ['name' => 'Oxímetro', 'price' => '39.90', 'image' => '../imagens/produtos/oximetro.webp'],
           ['name' => 'Permetrina', 'price' => '39.90', 'image' => '../imagens/produtos/permetrina.webp'],
           ['name' => 'Prednisona', 'price' => '39.90', 'image' => '../imagens/produtos/prednisona.webp'],
           ['name' => 'Rinosoro', 'price' => '39.90', 'image' => '../imagens/produtos/rinosoro.webp'],
           ['name' => 'Risperidona', 'price' => '39.90', 'image' => '../imagens/produtos/risperidona.webp'],
           ['name' => 'Rivaroxabana', 'price' => '39.90', 'image' => '../imagens/produtos/rivaroxabana.webp'],
           ['name' => 'Soro Fisiológico', 'price' => '39.90', 'image' => '../imagens/produtos/soroFisiologico.webp'],
           ['name' => 'Spray para Garganta', 'price' => '39.90', 'image' => '../imagens/produtos/sprayparagarganta.webp'],
           ['name' => 'Telmisartana', 'price' => '39.90', 'image' => '../imagens/produtos/telmisartana.webp'],
           ['name' => 'Trauma C Aerossol', 'price' => '39.90', 'image' => '../imagens/produtos/traumacAerossol.webp'],
           ['name' => 'Tylenol', 'price' => '39.90', 'image' => '../imagens/produtos/tylenol.webp'],
           ['name' => 'Valsartana', 'price' => '39.90', 'image' => '../imagens/produtos/valsartana.webp'],
       ],
   
       'Nutrição' => [
           ['name' => 'Vitamina D', 'price' => '39.90', 'image' => '../imagens/produtos/vitaminaD.webp'],
           ['name' => 'Suplemento Alimentar', 'price' => '39.90', 'image' => '../imagens/produtos/suplementoAlimentar.webp'],
       ]
   ];

   